export interface IndicateurRef {
  numero: number;
  code: string;
  critere: number;
  titre: string;
  description: string;
  niveau_attendu: string;
  exemples_preuves: string;
  applicable_cfa: boolean;
}

export const INDICATEURS: IndicateurRef[] = [
  // Critère 1 - Conditions d'information du public
  {
    numero: 1, code: "I1", critere: 1,
    titre: "Information du public sur les prestations",
    description: "Le prestataire diffuse une information accessible au public, détaillée et vérifiable sur les prestations proposées : prérequis, objectifs, durée, modalités et délais d'accès, tarifs, contacts, méthodes mobilisées et modalités d'évaluation, accessibilité aux personnes handicapées.",
    niveau_attendu: "Présence et mise à jour d'un support d'information (site web, plaquette, catalogue) contenant l'ensemble des éléments requis.",
    exemples_preuves: "Site internet, catalogue de formations, plaquettes, fiches programmes, CGV",
    applicable_cfa: true,
  },
  {
    numero: 2, code: "I2", critere: 1,
    titre: "Indicateurs de résultats",
    description: "Le prestataire diffuse des indicateurs de résultats adaptés à la nature des prestations mises en œuvre et des publics accueillis.",
    niveau_attendu: "Publication d'indicateurs chiffrés (taux de réussite, taux d'insertion, taux de satisfaction, taux de rupture pour les CFA).",
    exemples_preuves: "Taux de réussite aux examens, taux d'insertion professionnelle, taux de satisfaction, taux de rupture de contrats d'apprentissage",
    applicable_cfa: true,
  },
  {
    numero: 3, code: "I3", critere: 1,
    titre: "Obtention des certifications",
    description: "Lorsque le prestataire met en œuvre des prestations conduisant à une certification professionnelle, il informe sur les taux d'obtention des certifications préparées, les possibilités de valider un/des blocs de compétences, ainsi que sur les équivalences, passerelles, suites de parcours et les débouchés.",
    niveau_attendu: "Information diffusée sur les taux d'obtention, les blocs de compétences, les équivalences et les débouchés.",
    exemples_preuves: "Taux d'obtention des certifications, fiches RNCP, informations sur les blocs de compétences, passerelles",
    applicable_cfa: true,
  },
  // Critère 2 - Identification précise des objectifs
  {
    numero: 4, code: "I4", critere: 2,
    titre: "Analyse du besoin du bénéficiaire",
    description: "Le prestataire analyse le besoin du bénéficiaire en lien avec l'entreprise et/ou le financeur concerné(s).",
    niveau_attendu: "Processus formalisé d'analyse des besoins en amont de la prestation.",
    exemples_preuves: "Questionnaires de positionnement, entretiens préalables, fiches de recueil des besoins, comptes rendus d'analyse",
    applicable_cfa: true,
  },
  {
    numero: 5, code: "I5", critere: 2,
    titre: "Objectifs, contenus et modalités",
    description: "Le prestataire définit les objectifs opérationnels et évaluables de la prestation.",
    niveau_attendu: "Les objectifs pédagogiques sont formalisés de manière opérationnelle et évaluable pour chaque prestation.",
    exemples_preuves: "Programmes de formation détaillés, fiches pédagogiques, référentiels de compétences, conventions de formation",
    applicable_cfa: true,
  },
  {
    numero: 6, code: "I6", critere: 2,
    titre: "Mise en adéquation des contenus",
    description: "Le prestataire établit les contenus et les modalités de mise en œuvre de la prestation, adaptés aux objectifs définis et aux publics bénéficiaires.",
    niveau_attendu: "Contenus pédagogiques cohérents avec les objectifs et adaptés aux publics.",
    exemples_preuves: "Déroulés pédagogiques, supports de cours, planning de formation, méthodes pédagogiques documentées",
    applicable_cfa: true,
  },
  {
    numero: 7, code: "I7", critere: 2,
    titre: "Adéquation des procédures d'évaluation",
    description: "Lorsque le prestataire met en œuvre des prestations conduisant à une certification professionnelle, il s'assure de l'adéquation du ou des contenus de la prestation aux exigences de la certification visée.",
    niveau_attendu: "Les évaluations sont conformes au référentiel de certification.",
    exemples_preuves: "Référentiels de certification, grilles d'évaluation, modalités d'examen, procédures de validation",
    applicable_cfa: true,
  },
  // Critère 3 - Adaptation des prestations
  {
    numero: 8, code: "I8", critere: 3,
    titre: "Positionnement à l'entrée",
    description: "Le prestataire détermine les procédures de positionnement et d'évaluation des acquis à l'entrée de la prestation.",
    niveau_attendu: "Outils et procédures de positionnement formalisés et mis en œuvre systématiquement.",
    exemples_preuves: "Tests de positionnement, entretiens individuels, évaluations diagnostiques, grilles de compétences initiales",
    applicable_cfa: true,
  },
  {
    numero: 9, code: "I9", critere: 3,
    titre: "Conditions de déroulement",
    description: "Le prestataire informe les publics bénéficiaires des conditions de déroulement de la prestation.",
    niveau_attendu: "Information complète et formalisée transmise aux bénéficiaires avant et pendant la prestation.",
    exemples_preuves: "Livret d'accueil, règlement intérieur, convocations, planning, informations pratiques",
    applicable_cfa: true,
  },
  {
    numero: 10, code: "I10", critere: 3,
    titre: "Adaptation de la prestation",
    description: "Le prestataire met en œuvre et adapte la prestation, l'accompagnement et le suivi aux publics bénéficiaires.",
    niveau_attendu: "Adaptation effective des parcours en fonction des besoins identifiés.",
    exemples_preuves: "Parcours individualisés, aménagements, comptes rendus de suivi, adaptations pédagogiques documentées",
    applicable_cfa: true,
  },
  {
    numero: 11, code: "I11", critere: 3,
    titre: "Atteinte des objectifs - évaluation",
    description: "Le prestataire évalue l'atteinte par les publics bénéficiaires des objectifs de la prestation.",
    niveau_attendu: "Évaluations formalisées permettant de mesurer l'atteinte des objectifs.",
    exemples_preuves: "Évaluations en cours et en fin de formation, bilans de compétences, grilles d'évaluation, attestations de fin de formation",
    applicable_cfa: true,
  },
  {
    numero: 12, code: "I12", critere: 3,
    titre: "Engagement des bénéficiaires",
    description: "Le prestataire décrit et met en œuvre les mesures pour favoriser l'engagement des bénéficiaires et prévenir les ruptures de parcours.",
    niveau_attendu: "Mesures formalisées de prévention du décrochage et de suivi de l'assiduité.",
    exemples_preuves: "Suivi d'assiduité, entretiens de remotivation, procédures de relance, indicateurs de suivi des abandons",
    applicable_cfa: true,
  },
  {
    numero: 13, code: "I13", critere: 3,
    titre: "Coordination des apprentissages (alternance)",
    description: "Pour les formations en alternance, le prestataire, en lien avec l'entreprise, anticipe avec l'apprenant les missions confiées, à court, moyen et long terme, et assure la coordination et la progressivité des apprentissages réalisés en centre de formation et en entreprise.",
    niveau_attendu: "Coordination formalisée entre le CFA et l'entreprise sur la progression pédagogique.",
    exemples_preuves: "Livret de suivi en entreprise, fiches de liaison, calendrier d'alternance, visites en entreprise, réunions tuteurs",
    applicable_cfa: true,
  },
  // Critère 4 - Adéquation des moyens
  {
    numero: 14, code: "I14", critere: 4,
    titre: "Moyens humains et techniques",
    description: "Le prestataire mobilise et coordonne les différents intervenants internes et/ou externes (pédagogiques, administratifs, logistiques, commerciaux…).",
    niveau_attendu: "Organisation formalisée des intervenants avec rôles et missions définis.",
    exemples_preuves: "Organigramme, fiches de poste, trombinoscope, liste des intervenants avec qualifications",
    applicable_cfa: true,
  },
  {
    numero: 15, code: "I15", critere: 4,
    titre: "Coordination des intervenants",
    description: "Le prestataire mobilise et coordonne les différents intervenants internes et/ou externes.",
    niveau_attendu: "Coordination effective entre tous les intervenants (réunions, outils de suivi).",
    exemples_preuves: "Comptes rendus de réunions pédagogiques, planning des intervenants, outils collaboratifs",
    applicable_cfa: true,
  },
  {
    numero: 16, code: "I16", critere: 4,
    titre: "Ressources pédagogiques",
    description: "Le prestataire met à disposition ou s'assure de la mise à disposition du ou des moyens matériels et humains, des ressources pédagogiques nécessaires.",
    niveau_attendu: "Ressources pédagogiques adaptées, à jour et accessibles.",
    exemples_preuves: "Inventaire des ressources, supports de cours, outils numériques, centre de ressources, bibliothèque",
    applicable_cfa: true,
  },
  {
    numero: 17, code: "I17", critere: 4,
    titre: "Conditions favorables",
    description: "Le prestataire assure les conditions favorables à la réussite de la prestation (accueil, locaux, équipements).",
    niveau_attendu: "Locaux et équipements conformes, entretenus et adaptés aux prestations.",
    exemples_preuves: "Plan des locaux, inventaire des équipements, registre de sécurité, procédures d'accueil",
    applicable_cfa: true,
  },
  {
    numero: 18, code: "I18", critere: 4,
    titre: "Référent handicap et accessibilité",
    description: "Le prestataire mobilise les expertises, outils et réseaux nécessaires pour accueillir, accompagner/orienter et former les publics en situation de handicap.",
    niveau_attendu: "Référent handicap désigné, partenariats avec les acteurs du handicap, aménagements possibles identifiés.",
    exemples_preuves: "Nomination du référent handicap, convention avec l'Agefiph/FIPHFP, procédures d'accueil PSH, aménagements réalisés",
    applicable_cfa: true,
  },
  // Critère 5 - Qualification des personnels
  {
    numero: 19, code: "I19", critere: 5,
    titre: "Compétences des formateurs",
    description: "Le prestataire met en place les procédures de recrutement et de sélection des intervenants et vérifie leurs compétences.",
    niveau_attendu: "Procédure de recrutement formalisée avec vérification des compétences.",
    exemples_preuves: "CV des formateurs, diplômes, attestations, procédure de recrutement, grilles d'entretien",
    applicable_cfa: true,
  },
  {
    numero: 20, code: "I20", critere: 5,
    titre: "Entretien et développement des compétences",
    description: "Le prestataire entretient et développe les compétences de ses salariés, adaptées aux prestations qu'il délivre.",
    niveau_attendu: "Plan de développement des compétences pour l'équipe pédagogique.",
    exemples_preuves: "Plan de formation interne, entretiens professionnels, attestations de formation continue, veille pédagogique",
    applicable_cfa: true,
  },
  {
    numero: 21, code: "I21", critere: 5,
    titre: "Compétences des intervenants externes",
    description: "Le prestataire s'assure de l'adéquation des compétences des intervenants externes (sous-traitants, co-traitants) aux prestations.",
    niveau_attendu: "Vérification et traçabilité des compétences des intervenants externes.",
    exemples_preuves: "Conventions de sous-traitance, CV des intervenants externes, évaluations des prestations",
    applicable_cfa: true,
  },
  {
    numero: 22, code: "I22", critere: 5,
    titre: "Formation continue de l'équipe",
    description: "Le prestataire détermine, mobilise et évalue les compétences des différents intervenants, internes et/ou externes, mobilisés dans la mise en œuvre des actions.",
    niveau_attendu: "Suivi formalisé des compétences et de la formation continue de tous les intervenants.",
    exemples_preuves: "Tableau de suivi des compétences, plan de formation, bilans annuels, certifications obtenues",
    applicable_cfa: true,
  },
  // Critère 6 - Inscription dans l'environnement professionnel
  {
    numero: 23, code: "I23", critere: 6,
    titre: "Veille légale et réglementaire",
    description: "Le prestataire réalise une veille légale et réglementaire sur le champ de la formation professionnelle et en exploite les enseignements.",
    niveau_attendu: "Veille formalisée et tracée sur les évolutions réglementaires.",
    exemples_preuves: "Abonnements spécialisés, notes de veille, comptes rendus d'actualisation, mises à jour des procédures",
    applicable_cfa: true,
  },
  {
    numero: 24, code: "I24", critere: 6,
    titre: "Veille des innovations pédagogiques",
    description: "Le prestataire réalise une veille sur les innovations pédagogiques et technologiques permettant une évolution de ses prestations.",
    niveau_attendu: "Veille active sur les évolutions pédagogiques et technologiques.",
    exemples_preuves: "Participation à des salons, conférences, webinaires, benchmarks, nouvelles technologies testées",
    applicable_cfa: true,
  },
  {
    numero: 25, code: "I25", critere: 6,
    titre: "Veille des évolutions métiers et compétences",
    description: "Le prestataire réalise une veille sur les évolutions des compétences, des métiers et des emplois dans ses secteurs d'intervention.",
    niveau_attendu: "Veille formalisée sur l'évolution des métiers et des compétences.",
    exemples_preuves: "Études sectorielles, fiches métiers actualisées, partenariats avec les branches professionnelles",
    applicable_cfa: true,
  },
  {
    numero: 26, code: "I26", critere: 6,
    titre: "Actions de partenariat et réseau",
    description: "Le prestataire mobilise les expertises, outils et réseaux nécessaires pour accueillir, accompagner/orienter les publics.",
    niveau_attendu: "Réseau de partenaires identifié et mobilisé selon les besoins.",
    exemples_preuves: "Conventions de partenariat, liste des partenaires, actions communes, participation aux réseaux professionnels",
    applicable_cfa: true,
  },
  {
    numero: 27, code: "I27", critere: 6,
    titre: "Insertion professionnelle des apprenants",
    description: "Le prestataire favorise l'insertion professionnelle des apprenants en développant des actions en lien avec le monde économique.",
    niveau_attendu: "Actions concrètes pour favoriser l'insertion professionnelle.",
    exemples_preuves: "Partenariats entreprises, ateliers TRE, forums emploi, suivi de l'insertion à 6 mois, job dating",
    applicable_cfa: true,
  },
  // Critère 7 - Recueil et utilisation des appréciations
  {
    numero: 28, code: "I28", critere: 7,
    titre: "Recueil des appréciations",
    description: "Le prestataire recueille les appréciations des parties prenantes : bénéficiaires, financeurs, équipes pédagogiques et entreprises concernées.",
    niveau_attendu: "Système formalisé de recueil des appréciations de toutes les parties prenantes.",
    exemples_preuves: "Questionnaires de satisfaction, enquêtes, entretiens, bilans de formation, conseils de perfectionnement",
    applicable_cfa: true,
  },
  {
    numero: 29, code: "I29", critere: 7,
    titre: "Réclamations et aléas",
    description: "Le prestataire met en œuvre des modalités de traitement des difficultés rencontrées par les parties prenantes, des réclamations exprimées par ces dernières, des aléas survenus en cours de prestation.",
    niveau_attendu: "Procédure formalisée de traitement des réclamations et des aléas.",
    exemples_preuves: "Procédure de réclamation, registre des réclamations, suivi des actions correctives, médiateur désigné",
    applicable_cfa: true,
  },
  {
    numero: 30, code: "I30", critere: 7,
    titre: "Mesure de satisfaction",
    description: "Le prestataire met en œuvre des mesures d'amélioration à partir de l'analyse des appréciations et des réclamations.",
    niveau_attendu: "Analyse formalisée des résultats et mise en œuvre d'actions d'amélioration.",
    exemples_preuves: "Synthèses des enquêtes, plans d'amélioration, indicateurs de satisfaction, évolutions constatées",
    applicable_cfa: true,
  },
  {
    numero: 31, code: "I31", critere: 7,
    titre: "Actions d'amélioration continue",
    description: "Le prestataire met en œuvre des actions d'amélioration continue à partir des résultats de l'analyse des appréciations.",
    niveau_attendu: "Démarche d'amélioration continue formalisée et documentée.",
    exemples_preuves: "Plan d'amélioration continue, revue de direction, suivi des actions, indicateurs de performance",
    applicable_cfa: true,
  },
  {
    numero: 32, code: "I32", critere: 7,
    titre: "Mesures pour les publics en situation de handicap",
    description: "Le prestataire recueille les appréciations des parties prenantes et met en œuvre les mesures d'amélioration spécifiques pour les publics en situation de handicap.",
    niveau_attendu: "Recueil spécifique des appréciations des PSH et actions d'amélioration dédiées.",
    exemples_preuves: "Enquêtes spécifiques PSH, aménagements réalisés, partenariats handicap, bilan des actions PSH",
    applicable_cfa: true,
  },
];
